import { Link } from 'react-router-dom'

export default function Privacy() {
  return (
    <div style={{ maxWidth: '720px', margin: '0 auto', padding: '3rem 1.5rem', fontFamily: 'Merriweather, serif' }}>
      
      <div style={{ marginBottom: '1.5rem' }}>
        <Link to="/" style={{ fontSize: '13px', color: '#2D3DCA', textDecoration: 'none' }}>
          ← back
        </Link>
      </div>

      <div style={{ marginBottom: '2rem' }}>
        <h1 style={{ fontSize: '28px', fontWeight: 700, color: '#1A1A1A', margin: '0 0 4px' }}>
          sense<span style={{ color: '#6da627' }}>US</span>
        </h1>
        <h2 style={{ fontSize: '22px', fontWeight: 600, color: '#1A1A1A', margin: '0 0 8px' }}>Privacy Policy</h2>
        <p style={{ fontSize: '13px', color: '#6B7280', margin: 0 }}>Last updated: July 11, 2026 — Version 1.0</p>
      </div>

      <div style={{ background: '#E6F1FB', border: '1px solid #0C447C', borderRadius: '8px', padding: '12px 16px', marginBottom: '2rem', fontSize: '13px', color: '#0C447C' }}>
        This privacy policy is effective as of July 11, 2026. By using senseUS, you agree to the practices described here.
      </div>

      {[
        {
          title: '1. Who We Are',
          content: `senseUS is operated and owned by Gudboi Enterprises, LLC, but will be a Delaware Public Benefit Corporation eventually. ("we," "us," or "our"). Our platform at senseus.app allows verified human beings to share their opinions on questions of public interest. We can be reached at privacy@senseus.app.`
        },
        {
          title: '2. Our Commitment to Privacy',
          content: `senseUS is built on a simple principle: your identity and your opinions are yours. We collect the minimum information necessary to verify that you are a real human being, and we never sell individual data. Our business model is based on anonymized, aggregate opinion data — not on profiling or targeting you as an individual. We do not display advertising.`
        },
        {
          title: '3. What We Collect and Why',
          content: null,
          subsections: [
            {
              title: '3.1 Information We Collect at Signup',
              bullets: [
                'Phone number — used for identity verification only. Your phone number is stored by our authentication provider (Supabase) solely to enable future logins. It is never stored in our application database, never used for marketing, and never shared with third parties beyond what is necessary for authentication.',
                'Date of birth — used solely to verify you are 18 or older. Not stored after this check.',
                'Birth year — stored for age-band analytics only. Full date of birth is never retained.',
                'First name — stored and displayed according to your display preference.',
                'Last initial — derived from your last name at signup. Your full last name is never stored.',
                'Display preference — whether you appear as First Name + Last Initial, First Name Only, or Anonymous.',
                'Anonymous display name — if you choose anonymous, one of 20 curated gender-neutral names is assigned.',
              ]
            },
            {
              title: '3.2 Optional Information',
              bullets: [
                'Country of residence — stored as a two-letter country code. This is your country of residence, not citizenship. You may decline to provide this.',
                'Avatar — an emoji character selected from a preset list.',
                'Bio — an optional one-line text description shown on your profile.',
              ]
            },
            {
              title: '3.3 Information Generated by Your Use',
              bullets: [
                'Votes — your responses to questions are stored permanently and cannot be deleted. Votes are linked to an internal anonymous account ID, never to your name or phone number in any exported form.',
                'Replies — if you participate in discussion threads, your replies are stored and displayed publicly under your chosen display name.',
                'Usage data — standard server logs including IP address, device type, browser, and timestamps.',
              ]
            },
            {
              title: '3.4 What We Deliberately Do Not Collect',
              bullets: [
                'Full date of birth (discarded after age verification)',
                'Full last name (discarded after last initial is derived)',
                'Phone number in our application database (retained only by Supabase Auth for login purposes)',
                'Gender or gender identity',
                'Race or ethnicity',
                'Nationality or citizenship',
                'Email address',
                'Location beyond country of residence',
                'Contacts, camera, microphone, or any device sensors',
              ]
            }
          ]
        },
        {
          title: '4. How We Use Your Information',
          bullets: [
            'Verify that you are a real human being with one account',
            'Display your chosen name in the platform',
            'Prevent duplicate accounts, fraud, and coordinated manipulation',
            'Calculate aggregate opinion statistics across our verified user base',
            'Produce anonymized, aggregate data products for business customers',
            'Send you verification codes via SMS when you sign in',
            'Comply with applicable law',
          ],
          after: 'We do not use your information to serve you targeted advertising. We do not build individual behavioral profiles for sale.'
        },
        {
          title: '5. How We Share Your Information',
          content: null,
          subsections: [
            {
              title: '5.1 What We Never Share',
              content: 'We never sell, rent, or share individual vote data or individual opinion records with any third party. No business customer ever receives data that could identify you individually.'
            },
            {
              title: '5.2 Aggregate Data Products',
              content: 'Our B2B data products consist exclusively of anonymized aggregate statistics — for example, "72% of verified users aged 25–34 in Canada answered yes to this question." These statistics contain no personally identifiable information.'
            },
            {
              title: '5.3 Service Providers',
              bullets: [
                'Twilio — SMS delivery for phone verification.',
                'Supabase — database and authentication infrastructure.',
                'Vercel — hosting and content delivery.',
              ],
              after: 'All service providers are bound by data processing agreements and are prohibited from using your data for their own purposes.'
            },
            {
              title: '5.4 Legal Requirements',
              content: 'We may disclose information if required by law, court order, or valid legal process. We will notify you of any such request to the extent permitted by law.'
            }
          ]
        },
        {
          title: '6. Data Retention',
          bullets: [
            'Votes are retained permanently — this is a deliberate integrity decision fundamental to the trustworthiness of our data.',
            'Profile information is retained for as long as your account is active.',
            'Phone number is retained by our authentication provider (Supabase) for login purposes only, and is not stored in our application database. Full date of birth is discarded immediately after age verification.',
            'Server logs are retained for 90 days for security and fraud prevention.',
            'If you delete your account, your profile information and display name are removed. Your votes are retained in anonymized form as part of our aggregate dataset.',
          ]
        },
        {
          title: '7. Your Rights',
          content: null,
          subsections: [
            {
              title: '7.1 Access and Export',
              content: 'You may request an export of your personal data at any time from within the senseUS app. Data exports are delivered by email within 48 hours. This intentional delay is a privacy protection: it prevents anyone from forcing you to produce your voting history on demand in real time. You may choose to export your full voting history or a topic-level summary only.'
            },
            {
              title: '7.2 Correction',
              content: 'You may update your display name, country, avatar, and bio at any time within the app.'
            },
            {
              title: '7.3 Deletion',
              content: 'You may delete your account at any time. Deletion removes your profile and personally identifiable information. Your votes are retained in anonymized form as part of the historical record of verified human opinion.'
            },
            {
              title: '7.4 Rights Under Applicable Law',
              content: 'Depending on where you live, you may have additional rights under applicable privacy law, including GDPR (EU/UK), CCPA (California), PIPEDA (Canada), and others. To exercise any of these rights, contact us at privacy@senseus.app.'
            }
          ]
        },
        {
          title: '8. Security',
          content: 'We implement industry-standard security measures including encryption in transit (HTTPS/TLS), encryption at rest, row-level security at the database level, and separation of identity data from opinion data. If you believe your account has been compromised, contact us at security@senseus.app.'
        },
        {
          title: '9. Children\'s Privacy',
          content: 'senseUS is not available to anyone under the age of 18. We verify age at signup and do not knowingly collect information from minors. If you believe a minor has created an account, please contact us at privacy@senseus.app.'
        },
        {
          title: '10. International Users',
          content: 'senseUS is operated from the United States. If you access our platform from outside the United States, your information may be transferred to and processed in the United States. For users in the European Economic Area, United Kingdom, or Switzerland, we rely on your explicit consent as the legal basis for processing your personal data. Certain countries are unavailable due to applicable sanctions law.'
        },
        {
          title: '11. Our Data Minimization Commitment',
          content: 'senseUS is designed from the ground up to collect as little personal information as possible while still achieving our mission of verified human opinion. Every data point we collect has a specific, documented purpose. We do not collect data "just in case." This policy, alongside our published Data Architecture Reference, constitutes our public record of what we collect and why.'
        },
        {
          title: '12. Changes to This Policy',
          content: 'We may update this Privacy Policy from time to time. We will notify you of material changes by posting a notice on the platform and updating the "Last updated" date above. Your continued use of senseUS after any change constitutes acceptance of the updated policy.'
        },
        {
          title: '13. Contact Us',
          bullets: [
            'Privacy inquiries: privacy@senseus.app',
            'Security concerns: security@senseus.app',
            'Mailing address: [ADDRESS — to be completed after entity formation]',
          ],
          after: 'We aim to respond to all privacy inquiries within 30 business days.'
        },
      ].map((section, i) => (
        <div key={i} style={{ marginBottom: '2rem' }}>
          <h2 style={{ fontSize: '18px', fontWeight: 700, color: '#2D3DCA', marginBottom: '0.75rem', paddingBottom: '6px', borderBottom: '1px solid #E5E7EB' }}>
            {section.title}
          </h2>
          {section.content && <p style={{ fontSize: '14px', lineHeight: 1.7, color: '#1A1A1A', marginBottom: '0.75rem' }}>{section.content}</p>}
          {section.bullets && (
            <ul style={{ paddingLeft: '1.5rem', margin: '0 0 0.75rem' }}>
              {section.bullets.map((b, j) => (
                <li key={j} style={{ fontSize: '14px', lineHeight: 1.7, color: '#1A1A1A', marginBottom: '4px' }}>{b}</li>
              ))}
            </ul>
          )}
          {section.after && <p style={{ fontSize: '14px', lineHeight: 1.7, color: '#1A1A1A' }}>{section.after}</p>}
          {section.subsections && section.subsections.map((sub, j) => (
            <div key={j} style={{ marginBottom: '1rem' }}>
              <h3 style={{ fontSize: '15px', fontWeight: 600, color: '#1A1A1A', marginBottom: '0.5rem' }}>{sub.title}</h3>
              {sub.content && <p style={{ fontSize: '14px', lineHeight: 1.7, color: '#1A1A1A', marginBottom: '0.5rem' }}>{sub.content}</p>}
              {sub.bullets && (
                <ul style={{ paddingLeft: '1.5rem', margin: '0 0 0.5rem' }}>
                  {sub.bullets.map((b, k) => (
                    <li key={k} style={{ fontSize: '14px', lineHeight: 1.7, color: '#1A1A1A', marginBottom: '4px' }}>{b}</li>
                  ))}
                </ul>
              )}
              {sub.after && <p style={{ fontSize: '14px', lineHeight: 1.7, color: '#1A1A1A' }}>{sub.after}</p>}
            </div>
          ))}
        </div>
      ))}

      <div style={{ borderTop: '1px solid #E5E7EB', paddingTop: '1.5rem', marginTop: '2rem', fontSize: '12px', color: '#6B7280', textAlign: 'center' }}>
        senseUS · real humans. real opinions. real truth. · senseus.app
      </div>
    </div>
  )
}