-- senseUS: grant select on the existing sponsored_queue view.
--
-- CORRECTION (this replaces an earlier version of this migration that
-- shipped in error): the previous version of this file assumed
-- `sponsored_queue` didn't exist anywhere, because grepping every
-- migration for the name turned up nothing, and rebuilt it from
-- scratch. That assumption was wrong -- `supabase db push` failed with
-- "cannot change name of view column sponsor_name to question_id",
-- which only happens when a view with that name already exists. It does:
-- it was created by hand at some point (same blind spot as the missing
-- RLS-policy migrations noted elsewhere in this history) and was never
-- captured in a migration file, so it was invisible to a grep-only
-- check. Pulling the live definition via pg_get_viewdef() confirmed its
-- eligibility logic already matches exactly what Admin.jsx's
-- statusLabels/canActivate code expects (including returning the raw
-- `status` value, e.g. 'waitlisted', for anything outside the
-- politics-domain-waitlisted branch, which Admin.jsx specifically
-- handles) -- the earlier rewrite would have been a real regression
-- (mislabeling non-political waitlisted rows as "Ready to activate")
-- had it not failed loudly instead of landing.
--
-- So: the view itself was never the bug. This migration leaves its
-- logic untouched and only adds what was actually missing -- a GRANT
-- that was never captured either, which is the far more likely cause of
-- the original symptom (a genuinely live sponsored question rendering
-- as "Queue (0)"): a permission-denied error on the query, silently
-- dropped by the old loadSponsoredQueue() code before this round's
-- Admin.jsx fix started surfacing query errors instead of swallowing
-- them.
--
-- This statement is a no-op if the grant already exists, so it's safe
-- to apply regardless of whether the grant theory turns out to be the
-- full story -- see BUGFIX_SUMMARY.md for the follow-up check.
-- ============================================================

grant select on public.sponsored_queue to authenticated;
